apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: silo-migration-credentials
  namespace: minio
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgBexswk6VGQk/zhlTpDKiNZWATa3Ie0eQWaQ7Rh50yJyclkzaBQiP6ZC1aezWsN7mHZKGcG8adKgQq4G+hGDmPDJ80yGl/zjbw3tFK1dXiG0l8ZYkoIOoO34a+p4AShfHwEgsvAox2dKerEAwBoielelUhq7vYI1BBvDy6uJ4AfiRwN0CckC9twmXrepLRogZswb3u8BYG96yAQ/KIyFlIjzok6nTxNjH5eZChg6HTEbTSs8PUsk7620v+drF2IZ9v+6Giw/ZsKPmVwplSxLQBNHQIU8XFy2r3hhdG9bSNBo7+ZAC4BgD/PV2wpFR9nopifq6EeQJhruXUjqksUO7pSPwuFkqXbec8SnenNwPzqp4WKZHrv78bWWF4XzVcxpa6FlVbIhSj8GJeriFebEltf27S9qKB9I5oAvNaLu0CQ0T/LDksEeG3FJal/S+gle55Ko0NcvDQbJRdXMGxpTSECicgj5JZ63++QNdBzKfJGUqrUJynLG2FW5v+ZF8O5dgke6kLsqqT6F1REEqdnW3QNaiDvO+SPFjA33WbIlr8hHFNOQwiPbJ18hRFZdh33dL7ve2uqsRkYfX/0RtRE50Z2/lEY+nFEgo+WMg2pyPw4qDxzOdSprFi60YSyeTabEyFRrtAngFOPyuIV0JW+TrJfA2VCE6VAp7wyHD+o7uCSdQFOTxNNSnXblCflW9pcyxk=
    CONSOLE_SECRET_KEY: AgAMnVveZBjnYa4Q5eXSWlN0sOdEnPDX4y4izCecCMoRx41ap9fmaCQoUlaYh3WqucQOD7N02UzwE1zDATJGfObqSf7i3XaPq/CsX0fpoBYcGtDcMm/aFKsaLzpyOV/chTQ5QDofZrI3eUfeFe4dmqB5gKT28AReQHF6aXYnuPj1Q0LkgsHG474TJeV5zHyUml0UvkqBecy5sA6+QU0/PV8BZJ2Ss7B82YPhXIj7boxHFmEm+wE3IKjGTy2n4xXd3NbdhsJqRqvIrHjquOFQEK98ZVRF6LtlqBXY+HCAa5F6W/yaUTKZXEYCRXA0UWpCZrn9ZxEYglwFdTPVg/R3+bVXBkab8kvJhGgW0SQL5qXDzVLyL2/+oQryBGBF5kQcKdZA/HwTzKGiav1FyUWCnrHisdIaWpEpjBUIPz+4vE92PwrDGLtNz0ya08RcVNrsYGPWjuitYZbZAo0geRquBw3bwm4zpp7/yfgYHfT5kXWULtlCEVejNYY3CRcVBG5s/P2jRF/XWdmV/ATseu7YIyqOyxXC7kn/u88R5OCTPIwaQg4vLC3rT5IKnmzdJMrvwXtr62BYT96j8gthfA7tUR0oJSIOCUTc9zUVl8pnUHEZVNogs6Um2uK3jk1FU03ZO0ZNypdDLERCj0ew7ZMwgW0bKQnDR82YRT5PrZU6Tl4VA3UI8PuKMwDt87aiUROvVHQ=
  template:
    metadata:
      name: silo-migration-credentials
      namespace: minio
    type: Opaque
