apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silo-shadow-data
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path-retain
