apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: silo-root-credentials
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgB51gjEsvuGqcmlMfw3deTThjG8V6kWI0FlepTxw2IknayHTpixennNv/G5oFI9Gd5meCMvuGknEk3E4soZsazsjQ/5x1/SvZjOltTdZjIbN9tPX4P8mlznX6lG+Sxbj6Pm9S3FxtQJRcjm0GLuvx847oq55VdUZBWOT+VsHOz+fXSewAcaNeiPYf2SQkugJXxwuzqpFxbB5XWSIjdHyb6SpiEW6C/ZVOoaUdN4hV0m4dYK28XoegZ/b3FRQdIeTiIWqskj4a+UKrIuS2eQyXiVR0WENs3v+2/InJ14Jx3DBtnijI4Z8ho7rv+9+jpIx3CpfRliTpt80nCHSlnMQsWMRUvOhDGl+Q4zVmaX44qlqnD9mfaAJtOa8TKySnPnS0u4QhCdVEIFUYZbkj/PhSnrgnXwwc9VVf3zSfOfGWZK9fURJac0/N2wYrzFvnGfU1M/ZHhJ2SBxWHrHGIA60s0uhDLiaxYfNdZ7NiGGlin2Ho1gaEmHLG78FQsnsUkv6YDzn5G0gJINSRnSCswnE1KC53BjnR5cgKXZcDs17kFAe/TayXBbP5rz60ftVOwqTsrtoW1/VU6Ja3RndNoYFK9W6ZB3LmkwQisOVQKfyl0KXEJz7Z4t0jsnIDpLsnc54aOFUb/XX4dMgSQODxH+pgfOjzPAv0paEqgbf7uu0btUO5n/xP/iGcLZyh/IqJXU0rk=
    MINIO_ROOT_USER: AgBbW3wt2ovj1Kk3WXPp5F4WgLcm6b4BY3ta/OdZnxselPX44HkwLvPO7jBAWD+XI22gdu0uozYRRSkNrR+ds+X9VTPxW9zQ6LPfHLRnsb64FtDZxvtbTqbirsUSUFcWXR2XPWS1IeEXkZ6LrEkUt7NOo9CT4ySh6y4h3nULpIIAI9XlYPjCOoQoXZOud3mlVEYCODTfQcgE6km9A4+N1+UeiKgIGBp1raTdBFVCauQkYXHQ6Xvsrnj8fAimQC/VcONiBNroluNeSBr4c3ygpH3/UucMOL0gT4X4pTzzBNArdDNnf7bXIB6Tjmrv5+pLIwqkL+i6weB9Ygeip1CYk08XyDPMcINnoOlDi7acJATuR4GpowgtGXe9A3ODckNbM965BRonxcNd6cOarnFgaGaSm9C1OoNosdnp/hbEblQTAf/0Yc5J/1AXc3jv8MJx1DQgbakpIdICq4kLrcGvZ1LriDgJAn3dT7vgu9lCUEZlms/p/8B14MMZV0eXfM+ao4AzpJLVDqvrUlWTCmxCN+udxOvJIZzEfKoW1maU4DFSAjPWBaUH7V2Ci19TNI6Iq44WBLiSbHz/DpxsbbvgBRilB+urXESH7xx9o7T3gfFaK9UWY1p1GoHqSWczu1ui66ncw6M+LFLRHR9CHwUq39uTmFZBecLA3X0OqdFeMoRnbE7SWxk/qI7Cr1k9ok3pYOI=
  template:
    metadata:
      name: silo-root-credentials
      namespace: minio
    type: Opaque
