---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: grafana-discord-webhook
  namespace: monitoring-grafana
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgCEP28FpYPYHUc4JOGaLJ2I+cxCw1iHZ4DNnINAAllN14dvZqMRcIzzgLd8DlAO/wUstSi6urgXqpqijHZimNqHmEuwDoi0rnDCRRwI1+bBvz4oCR7SzeugBj9In/KM1M9EwNHL5yIy87KEILDa26VmUM2dtHmFHnDI1wy/DC4v4ygF2KrGKkRrSb+RGqMdcTNvErlFnV6k02bnGTksg0h+Iu24eMKbfAgIwLFxYSpcV9+O8XvjbUw9+fnFP//mffPF9CI6gI0GkIn8cNbB1AsgmguWvaTvVgZ6QB7I/yL/CyChmCPke3gJ4RGHeIakDU+KoPLtyI+NspseLt0kr5G3fBgrY5cNT54low6SVeqdezY3hUy+wLUj80Y6kavp4shtNcQ3kD0UdB7X+MJDiiTFAN/Ih5lknKEcGqsVWRPXDUh4JE2xw2hA/zbiHUT0d6XjefgAKWRhA7MXHTP3Dbkw2V/a9LGPBJraoipVkg2Mh8xtYTgy1clxrH1Mrb+mYA2LEgT5wupyfufsi3C2LE3M65YTWfFGy67UEY5Sg6Oqi+P5uKwr1AC5XTTjqaiLtxHO+P0mDgcF86m0xnnMqKMT9rx6FTEpphA15StWoyZj99kbHtljsxzFzpbPTcEqhddM82uy2JcZYus54uC5FZrjthK4bqtp6x+8SSURlMclvFqGCRTPwKk4IuojMZDvfGD96m+AQTadrz1g2MgamqDrYj4KgNdbCGoyh3zpP+vTcGhUQjT9B4d85kafZqlR2J3NBgejeeynSRFRjIGNrpwFNZytvPQHgkPx7J7mXQhT42WubyxZWF993X8cPUpqxNtZu+Eped1T9WZV58WEpmDF3RvyxBbelBkT
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: grafana-discord-webhook
      namespace: monitoring-grafana
