apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../cert-manager

patches:
  - path: HTTPRoutes.yaml
    target:
      kind: HTTPRoute
      name: rabbitmq-console-httproute
