apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-credentials
  namespace: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  # values are null on purpose, to be filled by kustomize patch
  encryptedData:
    username: null
    password: null
  template:
    metadata:
      creationTimestamp: null
      name: admin-credentials
      namespace: rabbitmq
      labels:
        rabbitmq.com/topology-operator: 'true'
    type: Opaque
