# [NOTE] Build image from the root directory of this repository.
# ex) ` docker build -f infra/backend/Dockerfile-client .`

### BUILDER ###
FROM node:18-alpine AS builder

COPY . /build
WORKDIR /build

RUN corepack enable
RUN pnpm --filter=backend deploy out

WORKDIR /build/out
RUN npx prisma generate
RUN npm run build client

### PRODUCTION ###
FROM node:18-alpine

ENV NODE_ENV=production
COPY --from=builder /build/out .
COPY ./infra/backend/entrypoint-client.sh .

ENTRYPOINT ["./entrypoint-client.sh"]
