# type UserDto {
#   id: ID!
#   title: String!
#   text: String!
#   isPublished: Boolean!
# }

type Query {
  getUsers: String
  getUser: String
}

type Mutation {
  createUsers: String
  updateUser: String
  deleteUser: String
}
