apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp-lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: '0.40.0'
      helm:
        releaseName: headlamp
        valueFiles:
          - $codedang/infra/k8s/headlamp/overlays/lab/values.yaml
    - repoURL: https://github.com/skkuding/codedang
      targetRevision: main
      ref: codedang
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
