apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  gatewayClassName: kube-system
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.codedang.com"
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-tls-secret
    allowedRoutes:
      namespaces:
        from: All