apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  gatewayClassName: traefik
  listeners:
  - name: http
    protocol: HTTP
    port: 8000
    allowedRoutes:
      namespaces:
        from: All

    # apex domain listener
  - name: https-apex
    protocol: HTTPS
    port: 8443
    hostname: "codedang.com"
    tls:
      mode: Terminate
      certificateRefs:
        - name: apex-tls-secret
    allowedRoutes:
      namespaces:
        from: All

  # wildcard listener
  - name: https-wildcard
    protocol: HTTPS
    port: 8443
    hostname: "*.codedang.com"
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-tls-secret
    allowedRoutes:
      namespaces:
        from: All

    # stage domain listener
  - name: https-stage-wildcard
    protocol: HTTPS
    port: 8443
    hostname: "*.stage.codedang.com"
    tls:
      mode: Terminate
      certificateRefs:
      - name: stage-wildcard-tls-secret
    allowedRoutes:
      namespaces:
        from: All

    # preview domain listener
  - name: https-preview-wildcard
    protocol: HTTPS
    port: 8443
    hostname: "*.preview.codedang.com"
    tls:
      mode: Terminate
      certificateRefs:
      - name: preview-wildcard-tls-secret
    allowedRoutes:
      namespaces:
        from: All