apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        enabled: true
        # Needed for the iris/kubernetes-apiserver ExternalName Service used by
        # the pprof TraefikService.
        allowExternalNameServices: true
