---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: alertmanager-discord-webhook
  namespace: monitoring-prometheus
spec:
  encryptedData:
    webhook-url: AgASNvGJerbNFLUTyXIh6Vdxu69uGQKwVfwUcIy6YwbcxUa3hQubbtITgxc0wLpU+ai5rrBu0PeMnQ+ACSO/TsoPKse4BCMy4H0TTHVnI6lRgy/ZOny2zliQqFdyfJuub88Yt7DbVzaibeiUrij6QRCyWbgkxUIJQTEqAiSLRWxNlJ9SN26CbgYs30WuoDASyqQV9RAjBeLMfz9Yn/e+7HOMCT7UrpgezDBGhdxrKeyMTfi5ddiO3hZ7Xrb3d92TWQu48D0q2DiuAgP3V5pNXS95//5OH39+RHLXc+x+L9Lg9ePdoN7YBNMDj+q59kutVatuY6LOMrBv6G1sjdpvW/YDx40qq2TFqUxYVaEJAqyqn00fASf2IFO7biPN683sUfPOIeQjtsFIfldqUsy6ROShlm50OgB4VnpM7qLjqu8TvTIgtIf2YWSzJ4jfyol61noE74I/dzUr+HA2y7crE+Ainyd1JB6Sv/pFE8kwT8ENh1hOEhvW+wlRdwlGhdFQJGbpMzZ+sqWGsd21pJO2PhGNThaRj6BWhRzQIVeDg8Zh440Sr8O/Dk/jd+DqewU9vKn20FnRfgpgZ9KXdFRT2570FIqaG/UGHH03sSY3H3Z9KrW2akl1ID+Q//99DyD3+c7lmiENabzpW1+aEcBI6vF+TDNbKHTj3/E3+YHFbb9+MVguBDmdtGhmUnvwVG78Rvmm999tvrihY+QyqVoVOVmvWh7FJuLBB485KnB57JV4TQda2ehGXkZ1pqvUg+ZM544B4nZsF7yFqINFeVfvWZaKcoTHpdAvqjgcrNM7c3lIIV28dYsbXLR89UlqXavVUBtMnyhyibCdgmxD2pgO9Sp89m361yTKQy7X
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: alertmanager-discord-webhook
      namespace: monitoring-prometheus
