---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring-prometheus
spec:
  encryptedData:
    webhook-url: AgB4Npkxh+inIVjMfp1jjY+v6rBoja+Z79NTzpNbVRlORi3ZyNE8SbkUeZOmmZ5VVzm93tEkzGHNLGW9W69O1Zg6z9Nx+bGkZJ0Hq35Ixv4rGD7/6zx7iFPgCK70TUN1bM4hgiFpJBOoREgZRAlv1XzfbMCobwHgMl7DnxBVT1dd/rq1nPPtOQWlNTdyGb+XD7oo+rTy3o0tPGaOS0GjcOC1qPfbjZSjpfQZXHACUvdMxWnKH2/gWgAvxGfA7TXYBDzL5VY4BWw6Yf1Ljqlj6N6xr6hPhwe/8QM417cg5qx7jUHB6KDvcauBu+axJXiXJAaymAjkDkr9OMxkp2oIkEPb9Nk///0eMJJlNQel3rFHTV6ZbjGoM0XpGnkupRdGHDptwQbdQAaVAsBTkbDuU6i03Sm30SMQuKWhd3qYBi6hV+ZSR0x4UasQ7DN/xotuMqexRAYL8STMaHy0csGZrRzXCRcb37RKeDJdyra8QW3pSs/O0REsHuNBAd38d5gW+oDC55npBLkxoIfyulo34NqvVSu6BNWpO2PZHC4rhuoHjbmCVLbl6dR7kNllt85Mk46o+wCPRgpaiIL5jqUDXLG/9eWCQAGSom8EUwf8exBl8ZmpNQQNynMTRrN3W5MMkrrabXWZ/FoHReEdELw8HxI7oEkEiG7hA5zNKehcY8oVuKmxWZZMgdOaaTfYjqcqrBd/XDZ9ww/6X5Y3w120iuES9ggjqrkH3B2GcjvDNZPWoQePWvX3cpSTUconP2XHahww/YKQkOa9mEipamLJgR2p+PLHE7Vb4hMnaFXJaq0MS8UfQXIU3SeODktAZdxFcjuYLw33k3ah+ZOhAtIE26zXOBvD5oT7IdwU
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring-prometheus
