apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - HTTPRoutes.yaml
  - backend-tls-policy.yaml
  - namespace.yaml
  - rabbitmq-cluster.yaml
  - service-monitor.yaml
  - tls-certificate.yaml
  - trust-manager.yaml

commonAnnotations:
  managed-by: kustomize
