apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq

resources:
  - admin-credentials.yaml
  - admin-user.yaml
  - HTTPRoutes.yaml
  - backend-tls-policy.yaml
  - namespace.yaml
  - rabbitmq-cluster.yaml
  - service-monitor.yaml
  - tls-certificate.yaml
  - vhost.yaml
  - topology-judging.yaml
  - topology-plagiarism.yaml
  - trust-manager.yaml

commonAnnotations:
  managed-by: kustomize
