apiVersion: cert-manager.io/v1
# namespace 간 참조 필요
kind: ClusterIssuer
metadata:
  name: rabbitmq-selfsigned-issuer
  namespace: rabbitmq
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-server-cert
  namespace: rabbitmq
spec:
  secretName: rabbitmq-server-certs
  issuerRef:
    name: rabbitmq-selfsigned-issuer
    kind: Issuer
  dnsNames:
    - rabbitmq.rabbitmq.svc.cluster.local
    - rabbitmq.rabbitmq.svc
    - rabbitmq
  duration: 8760h
  renewBefore: 720h
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: rabbitmq-ca
  secretName: rabbitmq-ca-secret
  issuerRef:
    name: rabbitmq-selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rabbitmq-ca-issuer
  namespace: rabbitmq
spec:
  ca:
    secretName: rabbitmq-ca-secret
---