apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iris

resources:
  - apiserver-service.yaml
  - configmap.yaml
  - deployment.yaml
  - deployment-test.yaml
  - deployment-rejudge.yaml
  - httproute.yaml
  - middlewares.yaml
  - namespace.yaml
  - rabbitmq-credentials.yaml
  - rbac.yaml
  - traefik-upstream.yaml

commonAnnotations:
  managed-by: kustomize
