apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iris

resources:
  - configmap.yaml
  - deployment.yaml
  - HTTPRoutes.yaml
  - namespace.yaml
  - rabbitmq-credentials.yaml
  - service.yaml

commonAnnotations:
  managed-by: kustomize
