{
  'kind': 'SealedSecret',
  'apiVersion': 'bitnami.com/v1alpha1',
  'metadata': {'name': 'n8n-credentials', 'namespace': 'n8n'},
  'spec':
    {
      'template': {'metadata': {'name': 'n8n-credentials', 'namespace': 'n8n'}},
      'encryptedData':
        {
          'notion-api.json': 'AgCCNJiTCtUrLORLILbR0nDhvInoCHrOZibzOuvXzBBylPp7QMdFHfpwtXD/FMXSHLrcwSEQMYLQ8R1LmOXAJVY5eb0PQ7oF71ArlJ9av5rA6LGqFyxlyNhz9McLTTC8hlOCSDhOXa7cr4pU4PH23NLwnLtjndxVKdv6GZA1IcUycHHE96Hk05SWbsYqtmSd0fg+qHfFVMRTgRD2PjFoc8LpP6beaH3bWJMG/+Mi8h2/O+U/ZxFTBm121us0VbGtZxQqeZuFY2lzmOlDgB4GUYrUGQwTT9gm7tH1ezW5Cos5ypQasbUxE6/m04CAp/27ZOy6+3RESCiRlefw07pLQo2fVim199Rj7vJZGOkIP+Fz7v6KhAS8LMdoq/0jYhaly7B6jM5mPs4Nn0L/ClrfBAfxnZfe0hjL1A5NIHfbiAkX/r9hm9ZCSkzHmHgESBzamNietBX7/vsnr4IfszB3P5ULSe2+ojUPvcd1I3can023mrDL1XtDRUyaj4fftOLLccy8urbrm8s09GkIG1+PbZC8HVW0+5SjQMGwlIuVW2r1pdCD6aa8iPT4CJ9hrpLcNYJMlHW3ZTwKjXuXj5F8EfkYczsnDvpaxfy3kxcZ+FQpI/5crYewv2f1hsEMSq5qk92pshd6D8fbK5UeZp3n/liAjyngaf6gb6cmfpKyPjxcxRQhBkMSPiOkFR9knaWZ1FFpsyCdwaYnJA9bLn9o31/EpHGPC9qb/fg04FX/fYk8QJjSC7EfA/L+6d2GnUzfaTNtacqVFUv9BpZg6/nuifoDCwxCq9EVp/XPXz/zm6ZBpS7pC91d2CC4nh7T+u6S95oIpe3xRcl1ZkrxLikU2J5nT8ANlQbpOd9hdWYvcbMTKCsrIhy2AMTRQ5l/OhvZ6w=='
        }
    }
}
