package handler

type ResultCode int8

const (
	ACCEPTED ResultCode = 0 + iota
	WRONG_ANSWER
	CPU_TIME_LIMIT_EXCEEDED
	REAL_TIME_LIMIT_EXCEEDED
	MEMORY_LIMIT_EXCEEDED
	RUNTIME_ERROR
	COMPILE_ERROR
	TESTCASE_ERROR
	SEGMENTATION_FAULT_ERROR
	SERVER_ERROR
	CANCELED
)
