apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iris

resources:
  - ../../base
  - aws-credentials.yaml
  - database-credentials.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: iris-env
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: iris
