---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pprof-basicauth-credential
  namespace: iris
spec:
  encryptedData:
    password: AgBU765PNLSlU6kkCGP/JheHIcDkSw1ZNS/WNQdrmA9uKUg30xiGh+m4UFEbu2rgMqVfFvn25rKZNFNcnQX4F1bgY7rHrRLqDrgH6jFGMHpmw2m/0CgVh3OE7bHY96CxD7CYDByU0L0GPMQNrhhuEcygtlb4bjBzAe4rBZmL8tQx3tMdvS9qEdq4ncMZFO16PvfClicyq+s3Mjmk9HCGGmX4K6BiUH4q02T7Vag4cT95K1Rs6YTpg9Uh3OGkQzZCeJzDxOSa/exfSzEu+9vJUXzFSHlVESFdTLKkMg08mno9VbnFyiBrAtBpkhl8ffGzpnuneFOytE8aN6M22UXWQ0/b4HTZBNiPARCqROm4vmq9mk1SofGqSENMmOMyAZ+QZMdin6R9tC+Tz+dxSYDr4a8eEdkEYijjDsgNL7BI1wwTU/E4Pam95kXjOWg8HS7ia73l9od913VhseRAHHRKB3Sb3v9vgtP0ckC47SPkeDtEGaNtPfIfa3O7HVb3kz8kJk8M1JsXPpB4NCz+sFaaE2hHb5W4WtgWivgQ8/yVlnxjJq18BcsIF7AMNX4TQTSWpQqWiIp9CreVEJUS92s9mbv/LIvW3H2yZSUxKexjeKi0b0blA8gkxWc1zQzB00/SejlFF+JCGOjK6/PVD9TLqiGHFKHvoYHWiRf6poAlwdShF+sNF93ZeoHb/pZEGUb0T2PiCbsglKitj9wfl8oGiG1Ic72ImHr3i7fHgnECnye+zoUxXaaJybp2y3j3vA==
  template:
    metadata:
      creationTimestamp: null
      name: pprof-basicauth-credential
      namespace: iris
    type: Opaque
