apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choesuna-react-app
  namespace: onboarding
spec:
  ingressClassName: traefik
  rules:
    - host: choesuna-react-app.first-task.codedang.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: choesuna-react-app
                port:
                  number: 3000
