apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: rabbitmq-ca
  secretName: rabbitmq-ca-secret
  duration: 8770h
  renewBefore: 720h
  issuerRef:
    name: rabbitmq-selfsigned-issuer
    kind: ClusterIssuer