apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pod-manager-servers-transport
  namespace: runner
spec:
  forwardingTimeouts:
    idleConnTimeout: 200s
    readIdleTimeout: 200s
    dialTimeout: 30s
    responseHeaderTimeout: 0s
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: pod-manager-traefik-service
  namespace: runner
spec:
  weighted:
    services:
      - name: pod-manager
        kind: Service
        port: 80
        serversTransport: pod-manager-servers-transport