apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/skkuding/codedang
        revision: t1802-migrate-observability-services-to-k8s # TODO: use main
        files:
          - path: 'apps/k8s/environments.json'
  template:
    metadata:
      name: 'grafana-{{.env}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: grafana
          targetRevision: 9.3.2
          helm:
            valueFiles:
              - $codedang/apps/k8s/observability/grafana/values-{{.env}}.yaml
        - repoURL: https://github.com/skkuding/codedang.git
          path: 'apps/k8s/observability/grafana'
          targetRevision: '{{.branch}}'
          ref: codedang
      destination:
        namespace: observability
        name: {{.env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
