apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/skkuding/codedang
        revision: t1802-migrate-observability-services-to-k8s # TODO: use main
        files:
          - path: 'apps/k8s/environments.json'
  template:
    metadata:
      name: 'loki-{{.env}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: loki
          targetRevision: 6.34.0
          helm:
            valueFiles:
              - '$codedang/apps/k8s/observability/loki/values-{{.env}}.yaml'
        - repoURL: https://github.com/skkuding/codedang.git
          path: 'apps/k8s/observability/loki'
          targetRevision: '{{.branch}}'
          ref: codedang
      destination:
        namespace: observability
        name: '{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
