apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/skkuding/codedang
        revision: t1802-migrate-observability-services-to-k8s # TODO: use main
        files:
          - path: 'apps/k8s/environments.json'
  template:
    metadata:
      name: 'minio-{{.env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://charts.min.io/
          chart: minio
          targetRevision: 5.4.0
          helm:
            valueFiles:
              - $codedang/apps/k8s/observability/minio/values-{{.env}}.yaml
        - repoURL: https://github.com/skkuding/codedang.git
          path: 'apps/k8s/observability/minio'
          targetRevision: '{{.branch}}'
          ref: codedang
      destination:
        namespace: observability
        name: '{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
