apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
data:
  config.yml: |
    mqtt:
      enabled: false

    tls:
      enabled: false

    detectors:
      cpu:
        type: cpu

    go2rtc:
      streams:
        usb_camera:
          - "ffmpeg:device?video=0&video_size=1280x720#video=h264"

    cameras:
      usb_camera:
        enabled: true

        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/usb_camera
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record

        detect:
          enabled: false
          width: 1280
          height: 720

        record:
          enabled: false