apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - aws-credentials.yaml
patches:
  - target:
      kind: CronJob
      name: sealed-secrets-backup
    patch: |
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: sealed-secrets-backup
      spec:
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                  - name: backup
                    env:
                      - name: S3_KEY_PREFIX
                        value: production
