apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-v18-pvc
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
