package sandbox

type StatusCode int8

const (
	RUN_SUCCESS StatusCode = 0 + iota
	CPU_TIME_LIMIT_EXCEEDED
	REAL_TIME_LIMIT_EXCEEDED
	MEMORY_LIMIT_EXCEEDED
	RUNTIME_ERROR
	COMPILE_ERROR
	SEGMENTATION_FAULT_ERROR
	SERVER_ERROR
)
