apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-beaver-pvc-longhorn
  namespace: cloud-beaver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
