export const PASSWORD_RESET_TOKEN_EXPIRATION_SEC = 300
export const PASSWORD_RESET_PIN_EXPIRATION_SEC = 300

export const PASSWORD_RESET_COOKIE_OPTIONS = {
  maxAge: PASSWORD_RESET_TOKEN_EXPIRATION_SEC * 1000,
  httpOnly: true
  // secure: true,
}
