apiVersion: v1
kind: ConfigMap
metadata:
  name: client-api-env
  namespace: client-api
data:
  MINIO_ENDPOINT_URL: 'https://minio.stage.codedang.com'
  KAKAO_CALLBACK_URL: 'https://stage.codedang.com/api/auth/kakao-callback'
  KAKAO_LINK_CALLBACK_URL: 'https://stage.codedang.com/api/auth/kakao-link-callback'
  FRONTEND_URL: 'https://stage.codedang.com'
