---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: grafana-discord-webhook
  namespace: monitoring-grafana
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgBGZt5OmcONDSOVaWJjO7gDvuPIln7kvOj6TfWGLdYZpLfcV5BkCSQCDUvDbZ6h6IqgKKDnFA8ulcT5S4p/gn8i36p1FNTTSjXdmpwuSZmFkONGPaC8f/6m/6DDA4o4CvfZS/nzZf8ryFhBA2AMRf/Bp8KJFNa53ruWBo/+4KvBF8mS5+OclPpIHBEdFruFs7B17TC1EEl6iJ1X9wJZ9w7tc27CMLdrTVSsniii16UpyRNgzv7U7+ZCTSzS4aGKcuiDSJVsR0nPhJSwR8O5IpwcdH3gQYfXf6vv/M//pubUJek8neklGeECxkxUbA+IfkKI0+6tUk680hcQLbScUXr5KZWHRz42IkO7htb2bfAHWafB1GsweY7lHKv9V4+6xlhLl7TytflL8/ecOJQPAS8AxtT8LlZigLWp1wOza/rDnAjKWyK5oVkhnWLqt1YbIp5+EUAyKYf7EtamLWGUk/TiPQgeco44v89Yu6JB//WPHLcYSXzNUgjdlzbTGP9yQwd1BV41XMUFhxP594OaGZn3sPA7ECatngdD09V+GqTlQv7uXGeOzh9XN1LHHBCPgn+HBMV68mD6Nyt9hsYlHcYLN+sUdANmAyVboccDsekZPaTXZWIxYymePQrMmf1lNf+iDEsMPQcoTOgJeqgyMIo/qKzi2IV6eq+CRwToUStmHe0cqAplqqPpOi2BN4gA01PxhJZion8UuX4fDa9PGgVTZ6UJNYc9AL6xv/H21PG5KDQs71tgw5tIyEmYLfFZfnCjOEiA9cY8Ijk0bD3m+2YBfnEc7Bt0QVMhCEhvKEMSeQ7E1j0QuDPW1UFM1NNq5M8JFo366GuDEDwWsWyG3FVg4hEGPvEnYJ/s
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: grafana-discord-webhook
      namespace: monitoring-grafana
