alerting:
  rules.yaml:
    apiVersion: 1
    groups:
      - orgId: 1
        name: AWS RDS
        folder: AWS Alerts
        interval: 5m
        rules:
          - uid: rds-free-storage-low
            title: RDS FreeStorageSpace Low
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: cloudwatch
                model:
                  dimensions:
                    DBInstanceIdentifier:
                      - terraform-20250506182211604800000001
                  metricName: FreeStorageSpace
                  namespace: AWS/RDS
                  period: '300'
                  region: ap-northeast-2
                  statistic: Average
              - refId: C
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 2147483648
                        type: lt
                      operator:
                        type: and
                      reducer:
                        type: last
                  type: classic_condition
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: 'RDS FreeStorageSpace < 2GB'
              description: 'RDS 인스턴스의 남은 디스크가 2GB 미만입니다.'

          - uid: rds-database-connections-high
            title: RDS DatabaseConnections High
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: cloudwatch
                model:
                  dimensions:
                    DBInstanceIdentifier:
                      - terraform-20250506182211604800000001
                  metricName: DatabaseConnections
                  namespace: AWS/RDS
                  period: '300'
                  region: ap-northeast-2
                  statistic: Maximum
              - refId: C
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 150
                        type: gt
                      operator:
                        type: and
                      reducer:
                        type: last
                  type: classic_condition
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: 'RDS DatabaseConnections > 150'
              description: 'RDS 인스턴스의 DB 커넥션이 150개를 초과했습니다.'
