apiVersion: v1
kind: Service
metadata:
  name: kjk-test-app
  namespace: onboarding
spec:
  selector:
    app: kjk-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP