alerting:
  contactpoints.yaml:
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: discord
        receivers:
          - uid: discord-default
            type: discord
            settings:
              url: $__env{DISCORD_WEBHOOK_URL}

  notification-policies.yaml:
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: discord
        group_by: ['grafana_folder', 'alertname']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
