{
 "title": "전체 서비스 로그",
 "description": "서비스 레벨에서 발생한 로그를 분석합니다.",
 "tags": [
  "log",
  "level-service"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ServiceName",
    "label": "서비스 이름",
    "query": {}
   },
   { "name": "TraceID", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "에러 개수",
   "type": "gauge",
   "description": "선택된 기간 동안 발생한 에러 로그 개수 입니다.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by() (rate({service_name=~\"$ServiceName\"} | detected_level = `error` [$__auto]))"
    }
   ]
  },
  {
   "title": "로그 개수 추이",
   "type": "barchart",
   "description": "시간에 따른 로그 개수",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (count_over_time({service_name=~\"$ServiceName\"} | detected_level != `error` [$__auto]))",
     "legendFormat": "{{detected_level}}"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"$ServiceName\"} | detected_level = `error` [$__auto]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "에러 로그",
   "type": "logs",
   "description": "시스템 운영에 치명적일 수 있는 오류만을 출력",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$ServiceName\"} | detected_level = `error`"
    }
   ]
  },
  {
   "title": "모든 로그",
   "type": "logs",
   "description": "에러가 아닌 모든 로그",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$ServiceName\"} | detected_level != `error` | line_format `[{{.detected_level}}] {{.req_method}} {{.req_url}} => {{.res_statusCode }} {{.err_message}} {{.message}}`"
    }
   ]
  }
 ]
}