{
 "title": "하드웨어 메트릭",
 "tags": [
  "metric",
  "hardware"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ServiceName", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  { "title": "인스턴스 개수", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "현재 인스턴스 개수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by(host_name) (system_cpu_utilization{service_name=\"CLIENT-API\"}))",
     "legendFormat": "CLIENT-API"
    },
    {
     "expr": "count(group by(host_name) (system_cpu_utilization{service_name=\"ADMIN-API\"}))",
     "legendFormat": "ADMIN-API"
    },
    {
     "expr": "count(group by(host_name) (cpu_usage_percent{service_name=\"IRIS\"}))",
     "legendFormat": "IRIS"
    }
   ]
  },
  {
   "title": "인스턴스 개수",
   "type": "timeseries",
   "description": "시간에 따른 인스턴수 개수 변화",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(group by(host_name) (system_cpu_utilization{service_name=\"CLIENT-API\"}))",
     "legendFormat": "Client"
    },
    {
     "expr": "sum(group by(host_name) (system_cpu_utilization{service_name=\"ADMIN-API\"}))",
     "legendFormat": "Admin"
    },
    {
     "expr": "sum(group by(host_name) (cpu_usage_percent{service_name=\"IRIS\"}))",
     "legendFormat": "Iris"
    }
   ]
  },
  { "title": "$ServiceName 실시간 CPU, Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "ServiceName" },
  {
   "title": "Total CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( + 25) * sum(avg_over_time(process_cpu_utilization{service_name=~\"$ServiceName\"}[5m])) * sum(avg_over_time(system_cpu_utilization{service_name=~\"$ServiceName\", system_cpu_state!=\"idle\"}[5m])) / count(sum by(instance) (avg_over_time(process_cpu_utilization{service_name=~\"$ServiceName\"}[5m])))",
     "legendFormat": "codedang-api"
    }
   ]
  },
  {
   "title": "CPU Utilization by Instances",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( + 25) * sum by(instance) (avg_over_time(process_cpu_utilization{service_name=~\"$ServiceName\"}[5m])) * sum by(instance) (avg_over_time(system_cpu_utilization{service_name=~\"$ServiceName\", system_cpu_state!=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( + 25) * (sum(avg_over_time(process_memory_usage{service_name=~\"$ServiceName\"}[5m])) / 2147483648) * sum(avg_over_time(system_memory_utilization{service_name=~\"$ServiceName\", system_memory_state=\"used\"}[5m])) / count(sum by(instance) (avg_over_time(process_memory_usage{service_name=~\"$ServiceName\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "EC2 CPU Utilization",
     "type": "timeseries",
     "description": "AWS EC2 > Codedang-API-Instance > Monitoring",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "25*sum by (instance) (avg_over_time(process_cpu_utilization{job=~\"backend-client-metric\"}[5m]))+25*sum by (instance) (avg_over_time(system_cpu_utilization{job=~\"backend-client-metric\", system_cpu_state!=\"idle\"}[5m]))",
       "legendFormat": "{{instance}}-cli"
      },
      {
       "expr": "25*sum by (instance) (avg_over_time(process_cpu_utilization{job=~\"backend-admin-metric\"}[5m]))+25*sum by (instance) (avg_over_time(system_cpu_utilization{job=~\"backend-admin-metric\", system_cpu_state!=\"idle\"}[5m]))",
       "legendFormat": "{{instance}}-admin"
      },
      {
       "expr": "25*sum(avg_over_time(process_cpu_utilization[5m]))+25*sum(avg_over_time(system_cpu_utilization{system_cpu_state!=\"idle\"}[5m]))",
       "legendFormat": "total_usage"
      }
     ]
    },
    {
     "title": "Service CPU Utilization",
     "type": "timeseries",
     "description": "AWS ECS > Codedang-API > Codedang-Client-API-Service > Health",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "( + 100) * sum(avg_over_time(system_cpu_utilization{service_name=\"CLIENT-API\", system_cpu_state!=\"idle\"}[5m])) * sum(avg_over_time(process_cpu_utilization{service_name=\"CLIENT-API\"}[5m]))",
       "legendFormat": "CLIENT-API"
      },
      {
       "expr": "( + 100) * sum(avg_over_time(system_cpu_utilization{service_name=\"ADMIN-API\", system_cpu_state!=\"idle\"}[5m])) * sum(avg_over_time(process_cpu_utilization{service_name=\"ADMIN-API\"}[5m]))",
       "legendFormat": "ADMIN-API"
      }
     ]
    },
    {
     "title": "컨테이너별 IRIS CPU 사용량",
     "type": "timeseries",
     "description": "컨테이너 별 IRIS CPU 사용량",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "cpu_usage_percent{service_name=\"IRIS\"}",
       "legendFormat": "{{container_id}}"
      }
     ]
    },
    {
     "title": "컨테이너별 IRIS 메모리 사용량",
     "type": "timeseries",
     "description": "채점에 사용되는 힙 메모리(MB)를 컨테이너 별 최대 할당 메모리(450MB)로 나눈 비율",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "memory_heap_bytes{service_name=\"IRIS\"} / (1024)^2 / 450 * 100",
       "legendFormat": "{{container_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Packets Dropped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "system_network_dropped_total{}",
     "legendFormat": "{{job}}: {{system_network_direction}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_network_errors_total{}",
     "legendFormat": "{{job}}: {{system_network_direction}}"
    }
   ]
  },
  {
   "title": "패킷 수신",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"receive\"}[1m]))",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"receive\", service_name=\"ADMIN-API\"}[1m]))",
     "legendFormat": "ADMIN-API"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"receive\", service_name=\"CLIENT-API\"}[1m]))",
     "legendFormat": "CLIENT-API"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"receive\", service_name=\"IRIS\"}[1m]))",
     "legendFormat": "IRIS"
    }
   ]
  },
  {
   "title": "패킷 송신",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"transmit\"}[1m]))",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"transmit\", service_name=\"ADMIN-API\"}[1m]))",
     "legendFormat": "ADMIN-API"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"transmit\", service_name=\"CLIENT-API\"}[1m]))",
     "legendFormat": "CLIENT-API"
    },
    {
     "expr": "sum(increase(system_network_io_total{network_io_direction=\"receive\", service_name=\"IRIS\"}[1m]))",
     "legendFormat": "IRIS"
    }
   ]
  }
 ]
}