---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pprof-basicauth-credential
  namespace: iris
spec:
  encryptedData:
    password: AgCWp74zIupj/V0HkRspgO+TutzjSnPdUPqTZydN23u7S++CrBU5/x/Ds/2Kpzvd/LsmV4SKQeCcsTR2k1nXr6gE5cX3rXpaSSuXvsxxjcJajijNseqAeqJfnYSrLsuMNfgWC1hcvs9ZerzUZO1zRso4JSSyahc/FL6TeBSdx4MVVM759F3BCtJJAZ92/ggjvHPr7s5vMv26+phkghwZKKAjCUDQolyU4ltAbGBXoOQEPs9MaPD2LYWOaJoHzwQktsk/2UZtBWyMSWVUnvCGpSgBKH6jUuV7c5QRxF6rRZYmGzp2tCEpVf3hw8M1Vr1QUiuFJakQUWebakWrAH8WYqQIvlu1YqHF/KG2qkYrXx5a3eAiExX8DroquIrakHg/0EzpM6V9uxZxqLbSMbRqpY40obNNE7GmHdfAw5jo+xb/PVsY9uTgkfQ2N4qqyf3NgmR61wtv2gKZVz8DWeyRRGu8Sdq2ka8iq7xs7Nw69ft8rhxV/RpKP6DQyBFC/DOBFgFSpXNgxVEAE3c1ZjkhQ2L7vo6MFByZi+6p0NTdCJBVAFYtLE9JmGY93vLOeczYvGjM13U4FJoLDGfRYisPfi0ZcW0iHfxBIHo53skhcKzo4xeT1yIT8NtYqiBVbFw6/fvnkYd2fFrrUsuQCJbOUiD2k0LWZZVJCNIKxk01I7Fa6/3N2Ln4I0+FQei4Hjzlvtm0zF3bkgCK3VocWHAH4rfnczNFZHK3tRWJ/GSQKtGQMAMNQk4S2U0VvlXqIg==
  template:
    metadata:
      creationTimestamp: null
      name: pprof-basicauth-credential
      namespace: iris
    type: Opaque
