apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-stage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
  labels:
    app.kubernetes.io/environment: 'stage'
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.11.1
    helm:
      releaseName: longhorn
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultReplicaCount: 3
          defaultDataPath: /var/lib/longhorn/
          replicaSoftAntiAffinity: false
        persistence:
          defaultClassReplicaCount: 3
          # No effect on local-path pods
          defaultClass: false
          reclaimPolicy: Retain
  destination:
    namespace: longhorn-system
    name: stage
  syncPolicy:
    automated:
      # Prune disabled: requires manual review before removing resources
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
