import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-3 p-3">
          <Link href="/">Main</Link>
          <Link href="/notice">Notice</Link>
          <Link href="/contest">Contest</Link>
          <Link href="/group">Group</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
