apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: observability
spec:
  encryptedData:
    rootPassword: AgC2Ma63NMrW+iNvtRqK5a0AuUGB0jPZsEashurnR6YAOtpKQJbAdhHRBj/v7A5AQ9eRa+T9Sd2+g66aCbPLb4noP2o075XvOuihJnj1WeGxTPsPxYHAPIqk0gOsoaFqxsjyK8F5L+HO1VxboU3hhXlkmF05zelF9UebXw+pmI6NvDbPnrXfh2uyN+7rLafTBx/zlzh/1gGTUFwEO4CS9yBMY5A2CEQAUcXw8UAsC7z3yv8goFGrsMM0vhgvXSKBfLP3Xb38IZOrmfcsizAkCS3O5fSkHLo4FUuvmT7fBosxP88rKbKGJeLYE4Aoceku0q2eGIzxRAQjYvjJETUIOF/k9xMwNUCQCeMAVP8U/xt1xoRkL0FaNlRGPdHf/lQ7WrXGavpl7BU/lTZy3YIgVG8YGpsDxf+76YML3ZKN7ycQmgosoTyQZQh7K/mOelOgCfbSoVbO0WqRwB+oNrQx0Df4ybDxVSstzilBdfOxE7K5o/+zTXrzFTq7JFyuV/0GARilxJJvDbIs9Qz7ekyP0bLevlksbi2/Otkpizc4IUCjBSQ8IuH4/IZJxIU2tq9GMnR6mmCH8Ba0IbsS3f98lqtFgnDcXGdHkydMEyqBhc6hgA8l13/vPBHqjVbwz7EBL0R4P8mBMAmujfjwuDLF63UYcr1ZtNJ6lwH6cExNI9vhk/tDAKAzPfiKZ8RMvmg5ygyPrQUoaHNsN6PF+A==
    rootUser: AgArDL8EJ8qxP4bH2CHeRti5j514llvhqJaXAceqPSVunYaTMLHe13KlPKQy+oJsnlQEKWei2Ht7uZ8dwjWNEyTdFSRAiZz3EhYhnU8EzGuLtmo+tvNGIvDx1CGq06GbJKJkIqoJSzh+bCfLMmrRN2OLFd0ckr1Z7lvHOIJesN/FcF5sFWtLQ9881CAWUbmzMzBEQlYVzSgClIEdR2wUmHg43qCv06HOqgTl8eN/1+o6B6B5fKhx3GNtemR7886I5rJBBJCmn3QxpRg0h0yJ9myMDSAFKVQvSpD+o1LPQtRCM5O5MS1xNyKSTKKjesquA//yHTbyOqKdL6VQLWjrAPNAPcuLGr5mp5aDRIdmIZRmLVlqQruzb+MpZ+Kow2Y6JLENL4WdRs2Rpz6MR3uGH6pvxb+XOC0IUnpNszKnTa+RMtpUZVAt0UPsSTbth2U2fAAvB6F4VU9wTtKZA7LwpZwhWV7Stprj7LbUAQiOBJlclGk/rVR4+L/4MWSM5R7Qf3m/MSxpnYgZ77dssIrVRsXl+yDaQ/P2AJ0Snqk5lcQUAhcwb3vyzWA99P1S+9CRfIaxj8AopdDBIldlqIa9ngVV4+7XLxXj1BzKD7z2YitNcxE3YptzxfZuG7IHRB3zSs5rjclbAWV9Yr8ChXlA2d6mJTY3h0PelM4zAq04au96m6dvQ9aNn9ar/d2HYOhvkBVAwLcB1r7hKw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: observability
    type: Opaque
