apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: observability
spec:
  encryptedData:
    accessKey: AgAHV8LJbyM2QZl4ZTBXQkVRC64oWwkuNx96jyDfTgmoaGEjDQmIc9g4JKEyOVoH87ncYHjbI14SKVAG8RfhO5G442UK4d4UeVmwG7Q8Egvxe8DVywFHwANlUGfhXi1UqhG/gltp4JsWqZ/iU5upRfDuoTQwnuAphFNtsso3Tk1O/RlMZYu2gMM4qPEgsKq3HD0TIXxQGkCxX0E+tVHi9bVgycU5tnItxGKDFoBtsm/NhvV3PwLA3nGCito07XmwD2iF0GGoVJQiDrKtMH+nS2wgDyjtasTk32Teuvy4f1l3qWn2UUNTYLcRlEIB5SVPAwSI8eXHYEDcdFE0wteTjOsJZaAk0/HHt6pq9yfi1XHcE/IRoDEM2fE8WvPsU1frwELezp18n4Urm83ibQYd1CYmM7C53w3SRrDXwGubSR7sGdqBNldCAlQgUH7fb/CKBLfzjKtkwuXbwBz8onm5a6gJV68HKeVyYKrtTz5ukVuDtGimt+VaIoN28g72+nSLcRG9ivBc0GB5RExXVJgV6QgHOccBRJituEihP8V2m8SrjwPL2HSeG+jgQUAgHKfqdn1sqNO9xJwPDUTFVkbxey8jjd8sTosklck6A+b1yky5/R7zFp1V+DAyZzqviBypMz+zGFXC8TmymCkYuaT/8WzjEPYQb0qAR+FzHl0NlvsRdrtVcbglGiYh5+LeEthJGc6lwg6Yx+a2Xg==
    secretKey: AgCeaZELXEFZeoo82VnTNCLIPjzTJuYkTN1nAYVmzQpykRIB4K4G85760fzp1UAZOThuu1XZI78PxUiGKjP5yx3GL8cFBVxDlmAvWPWN1y0+XvsjIQHka6PQEQdOf3F5IUgHllwfob+ez2RciPcibQO6TvOp9Lqv72QvOZoS5yxgpTrOiefYSqABs6bAx6ab6DA0eqpwKPO5KJgH2El0tuum7xKfU8NfvlQIqhPyqSHxnUEQ8ahl//dYKjPWrAArpdiYCHYAkRvTLHcnVanSFc6P7m0v6PffngbOeInDjBVYe6JvzFfLYSF9uFnjo6ugYTJ2D0oD5yaRyk3UhD2ic78HbAATRB0Vv5qMja6Eo73LJotPNidGtidcdwj8G6GjeL4xdi9ivqGnjMLcQt7SJ/hrHii6qhNdtX50uvFQF/FtF5wpc9d1I93KGxedDknfcJ75cd9QcXx5BSc5CT78iYsQKyA+46egjeBkHIET2ut3vpF8A0IunkvUtjZtZV6EMF9pkfVblMmyPtnBBRGxaRrmOkpP9Lpg0f3gY7FJGG9rE3m3qXmLTErL8h3gVjhcSrLaIPvX4ayKeAZlcVwa8KAYhnaDHCcKJSTzTvEhH53r43wx1zwHlOREbrx0/LukYO8bOtRwVoMyLyOu9lGcEgI9khClpyBpm0+e4iPiNoTcB4CRfSLY6ogrDqAmTOIFCpZIVAY36/1Xaa1LnQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: observability
    type: Opaque
