mode: standalone

accessKey: minioadmin
secretKey: minioadmin

persistence:
  enabled: true
  size: 8Gi
  accessMode: ReadWriteOnce

# TODO: add Minio console
service:
  type: ClusterIP
  port: 9000

# list of default buckets created after Minio install
buckets:
  - name: loki-chunk
  - name: loki-ruler
  - name: loki-admin
# metrics:
#   serviceMonitor:
#     enabled: true
#     additionalLabels:
#       service.name: minio
#       interval: 15s
