mode: standalone
auth:
  existingSecret: minio-secrets
persistence:
  enable: true
  size: 8Gi
  # existingClaim: minio-dynamic-pvc
service:
  type: ClusterIP
  ports:
    api: 9000
console:
  service:
    type: ClusterIP
    ports:
      http: 9001
# defaultBuckets:
#   - name: loki-chunk
#     policy: none
#   - name: loki-ruler
#     policy: none
#   - name: loki-admin
#     policy: none
